name: Verify Emails Cluster

on:
  workflow_dispatch:

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取代码
        uses: actions/checkout@v4
      - name: 设置 Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: 极速验证
        run: python verify.py 0 5  # 参数0表示不切片，参数5表示把当前输入的完整文件切成5份
      - name: 上传结果
        uses: actions/upload-artifact@v4
        with:
          name: result-${{ github.run_id }}
          path: result_*.txt
